language: c

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - cppcheck
      - clang-3.5

script:
  - cppcheck --enable=all --error-exitcode=1 --inconclusive main.c fiche.c
  - make
  - scan-build --status-bugs make -B
